BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role,full_name, email, zip_code, address)
VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER','cristina shim', 'cristina@gmail.com', 1414, 'pepito 223');
INSERT INTO users (username,password_hash,role,full_name, email, zip_code, address)
VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN','sofia costanzo', 'sofia@gmail.com', 1414, 'pepito 546');

INSERT INTO type_of_food (categories_name) VALUES ('Vegetarian');
INSERT INTO type_of_food (categories_name) VALUES ('Vegan');
INSERT INTO type_of_food (categories_name) VALUES ('Gluten free');
INSERT INTO type_of_food (categories_name) VALUES ('Pizza');
INSERT INTO type_of_food (categories_name) VALUES ('Burgers');
INSERT INTO type_of_food (categories_name) VALUES ('Pastas');
INSERT INTO type_of_food (categories_name) VALUES ('Mexican');
INSERT INTO type_of_food (categories_name) VALUES ('Asian');
INSERT INTO type_of_food (categories_name) VALUES ('Peruvian');
INSERT INTO type_of_food (categories_name) VALUES ('Grill');
INSERT INTO type_of_food (categories_name) VALUES ('Seafood');
INSERT INTO type_of_food (categories_name) VALUES ('Indian');
INSERT INTO type_of_food (categories_name) VALUES ('Healthy');

INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Sacro', 'Trendy restaurant offering a menu of gourmet vegan dishes in a stylish space that has a bar.',  1139700215, 5, 'Wonderful dining experience, great atmosphere with delicious unique cocktails and food! Would highly recommend',  'https://images.happycow.net/venues/1024/14/66/hcmp146668_766381.jpeg ', 1414, 'http://www.sacro.com.ar/', 'Costa Rica 6038, CABA');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Loreto Garden Bar ', 'A small restaurant with healthy and original proposals in the middle of a dream neighborhood.', 1145557170, 4, 'A very good and surprising option to eat in a residential neighbourood. The service is very gentle and the food is the best!', 'https://colegialesnoticias.com.ar/barrio/wp-content/uploads/2021/04/loreto-garden.jpg', 1426, 'https://www.instagram.com/loretogardenbar/?hl=es', 'Virrey Loreto 2912, CABA');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Estilo Veggie',  'Vegetarian street food restaurant.', 1134050051, 3, 'This place is an oasis in Argentina, with tofu that makes your heart soar!',  'https://www.infobae.com/new-resizer/S8BeR4_0sRMuDZLhWxalywfcHKY=/992x661/filters:format(webp):quality(85)/arc-anglerfish-arc2-prod-infobae.s3.amazonaws.com/public/IU3SGBJQBVBAXOUV4ZW4S6T6E4.jpg', 1419, 'https://estiloveggie.com.ar/shop/', 'Paraguay 4674, CABA ' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('BIO Restaurant', 'Restaurant and Catering Service that only creates dishes using organic ingredients, healthier options, with nutritional quality, and free from contaminants.', 1147743880, 5, 'I always check out the Raw Vegan places when I travel and Bio Solo offers a very nice experience with delicious, not overly-complex raw meals in a cool environment.', 'https://media-cdn.tripadvisor.com/media/photo-s/11/ff/82/b8/photo3jpg.jpg', 1414, 'https://biorestaurant.com.ar/', 'Humboldt 2192, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address)VALUES ('Buenos Aires Verde', 'Patrons can explore a menu crafted exclusively from organic ingredients, prioritizing health and environmental well-being.', 47759594, 5, 'We thoroughly enjoyed our 2 lunches at this wonderful vegan-vegetarian restaurant. Unique, interesting selection of healthy beverages.', 'https://images.happycow.net/venues/1024/16/74/hcmp16747_866013.jpeg', 1419, 'https://bsasverde.com/', 'Jose Ignacio Gorriti 5657,CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Lado V', 'Serene place with a relaxed atmosphere where they serve beer and cocktails specializing in plant-based dishes.', 1531671919, 4, 'We tried three different items and all of them were just great, but the vegan burger was one of the best I have ever had. Flavorful and beef-like without trying to make it "just like a burger" It was simply delicious.', 'https://images.clarin.com/2021/08/11/street-food-plant-based-en___Ir1Oz2b8i_1200x0__1.jpg', 1426, 'https://www.instagram.com/ladov.bsas/?igshid=YmMyMTA2M2Y%3D', 'Honduras 4969, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Amador Cantina', 'Amador, an elegant vegan neo-cantina with comfortable and abundant dishes.', 1156335654, 4, 'One can enjoy vegetarian or vegan dishes with peace of mind, full of flavor and great taste. Applause to the kitchen! The service is very friendly. Additionally, they are pet-friendly', 'https://www.clarin.com/img/2022/06/09/KF794HZVe_2000x1500__1.jpg', 1414, 'https://www.amadores.com.ar/', 'José A. Cabrera 5991, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Let it V', 'Mother Natures food Fusion of flavors, aromas and cultures that create unique dishes. 100% plant based and gluten free.', 1122548183, 4, 'One of the best meals I had in Argentina. Everything we ordered was delicious and service was great. Recommend getting a reservation if you want to sit on the patio.', 'https://static.wixstatic.com/media/9bb757_5286107f8a2846ff9336e069232259ff~mv2.jpg/v1/crop/x_0,y_523,w_3532,h_4253/fill/w_728,h_876,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/_MG_7712%20(1).jpg', 1419, 'https://linktr.ee/letit_v', 'Costa Rica 5865, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Vurguesa', '100% plant-based burger joint', 1144226538, 3, 'Delicious food at a great price, highly recommended as a vegan option!', 'https://images.hola.com/imagenes/cocina/recetas/20190819146554/hamburguesas-vegetarianas-recetas/0-705-227/hamburguesas-veggies-t.jpg?tx=w_1200', 1426, 'https://www.instagram.com/vurguesa_vegan/', 'Av. del Libertador 6536, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Mudrá', 'Mudrá is a plant-based restaurant for all tastes and everyone. On a unique rooftop, in the heart of Buenos Aires.', 1150009717, 5, 'I cant understand anyone giving this place less than a 5. It was literally the best vegetarian/vegan food I have ever had. All four of us in attendance agreed (even the meat-eater) that this was a truly memorable meal.', 'https://pbs.twimg.com/media/FM8EuBVWYAYGkuL.jpg', 1414, 'https://mudra.com.ar/', 'Av. Córdoba 3942, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Sintaxis Palermo', 'Sintaxis is the dream come true of a family that imagined a different place. On July 17, 2012, the first restaurant in Argentina with strictly gluten-free cuisine opened its doors.', 1156535755, 3, 'Lovely gluten free restaurant! My husband who is the celiac of the family was pleased with the prices and selection of foods! I had salmon ravioles and they were filling and delicious!', 'http://www.sintaxisglutenfree.com/assets/img/fotosurquiza/urquiza-1.jpg', 1419, 'https://www.sintaxisglutenfree.com', 'Nicaragua 4849, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ( 'Eggs & Green Cafe', 'A small venue brimming with 100% gluten-free options, also pet-friendly', 1165548505, 4, 'There are so many delicious choices to choose from! I really wanted half of the menu.', 'https://salpimenta.com.ar/wp-content/uploads/2021/03/unnamed-25-2-1068x601.jpg', 1426, 'https://eggsandgreens.com/carta', 'Soldado de la Independencia 670, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Hierbabuena', 'Organic restaurant and market,all gluten-free.', 1143622542, 3, 'Really tasty and hospitable. Unique flavours and a great menu that accommodated our every need. Very good service and really nice cooking staff', 'https://media-cdn.tripadvisor.com/media/photo-p/1a/a1/39/77/photo6jpg.jpg', 1414, 'https://www.instagram.com/hierbabuenarestaurant/?hl=es', 'Av. Caseros 454,CABA '  );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('L´adesso', 'A discreet restaurant serving classic Italian dishes in a charming dining room or on a garden terrace.', 1138075492, 4, 'Very kind and attentive service. The starters are great, no too many options for primo and secondo, but all of the of exceptional quality.', 'https://static.wixstatic.com/media/5c7e7c_c19581923ef74eee872eaf90db6c5648~mv2.jpg/v1/fill/w_454,h_341,fp_0.50_0.50,q_90,enc_auto/5c7e7c_c19581923ef74eee872eaf90db6c5648~mv2.jpg', 1419, 'https://www.instagram.com/ladesso_ristorante/', 'Fray Justo Santa Maria de Oro 2047, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Ronconcon', 'Authentic Latin cuisine featuring flavors from Mexico, Colombia, Peru, Venezuela, and more, paired with boutique wines and the finest cocktails.', 1120855860, 5, 'This was place has a ton of heart; amazing food, original cocktails, and staff that aims to please. Get the house made jalapeño hit sauce for an extra kick.', 'https://media-cdn.tripadvisor.com/media/photo-s/17/1a/b6/22/ronconcon-cocina-latina.jpg', 1426, 'https://www.instagram.com/ronconcon.ba/?hl=es', 'Calle Beauchef 527, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Guerrin', 'Iconic Pizzeria located on Corrientes Avenue. A symbol of Buenos Aires pizza.', 43718141, 5, 'A must-visit in Buenos Aires. A classic you cant miss; the pizza is delicious, loaded with lots of cheese, and the service is fast. We definitely recommend it!', 'https://pbs.twimg.com/media/FBJM8p8XsB8iQaE.jpg', 1414, 'https://www.instagram.com/pizzeriaguerrin/', 'Av. Corrientes 1368, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('El Cuartito', 'An icon of the City of Buenos Aires. The walls of El Cuartito are overflowing with autographed photos, jerseys worn by football idols, some of whom still lean on the counter to indulge in the traditional feast, the elixir of the gods, of pizza and moscato.', 1148161758, 5, 'Good quality pizza and empanadas. The ham fugazza is spectacular. The waitstaff is always efficient. It gets better with time, they have Wi-Fi, and you can pay with credit and debit cards.', 'https://turismo.buenosaires.gob.ar/sites/turismo/files/p980_elcuartito.jpg', 1419, 'https://www.instagram.com/cuartito_paginaoficial/', 'Talcahuano 937, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('El palacio de la pizza', 'Iconic Buenos Aires pizzeria. From its sidewalk, you can admire the majestic proximity of the obelisk.', 1143229762, 4, 'One of the many classic pizzerias on Corrientes Avenue. You can eat standing up or seated at the back of the dining room. Pizza by the slice, a classic place, waiters from days gone by with years of experience. If you pass by, its worth having a slice.', 'https://turismo.buenosaires.gob.ar/sites/turismo/files/p980_elpalaciodelapizza.jpg', 1426, 'https://www.instagram.com/palaciopizza/?hl=en', 'Av Corrientes 751, CABA'  );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('El imperio de la pizza', 'Pizzeria located at the far end of Corrientes Avenue, at its intersection with Federico Lacroze Avenue, in front of the terminal station of the Urquiza Railway and near the entrance to the Chacarita Cemetery.', 1145530875, 4, 'A traditional place and the best Fugazzetta Ive ever tasted. The mozzarella pizza is also very delicious, with a thin crust, cooked to perfection.', 'https://turismo.buenosaires.gob.ar/sites/turismo/files/fachada-pizzeria-imperio-chacarita-1500x610.jpg', 1414, 'https://www.instagram.com/elimperiodelapizza/?hl=en', 'Av. Corrientes 6899, CABA'  );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Banchero', 'In the neighborhood, Av. Almirante Brown proudly showcases the best pizzerias, and without a doubt, Banchero is the most traditional. Its the place where Fugazza with cheese was invented.', 1143011406, 4, 'The typical Buenos Aires pizza: lots of cheese, generous slices. The one with vegetables and béchamel sauce is simply the best. Good empanadas too.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrSnyRAdLTWteRMUN5dbw089Y6lv-9I7WOIg&usqp=CAU', 1419, 'https://www.instagram.com/pizzeriabanchero/?hl=en', 'Av. Almirante Brown 1200, CABA'  );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Menenga', 'Burgers in a snug dining room with an edgy vibe, plus sidewalk tables.', 1164378166, 4, 'Excellent burgers! The sauces that came with the ones we ordered were very good. Special mention for the Cabutia bread: fantastic. The beers were okay, but not the best you can find in the area. Another thing to mention is the speed of service. The waitresses were very attentive and helpful. Highly recommended overall.', 'https://media-cdn.tripadvisor.com/media/photo-m/1280/22/e9/4f/0b/fachada.jpg', 1426, 'https://www.instagram.com/menengaresto/?hl=en', 'Espinosa 480, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Big Pons', 'A chain of burger joints, leveraging good service and good quality. Standouts are the double-patty burgers with crispy onions and premium bacon, as well as the craft draft beer.', 1156997329, 4, 'Excellent burgers, among the best in Argentina. The owners really know how to make an outstanding product. From the bun to the meat blend they use for their burgers, everything is perfect. There s usually a wait to eat, but it s worth it.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1ivY5nQIDvIV2-yvQOZUcIXKToB0CULroFWrTaPfRl9GiWhsSjQketm0gpMgzFTLwulg&usqp=CAU', 1414, 'https://www.bigpons.com.ar/', 'Fitz Roy 1727, CABA'  );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Arredondo', 'A bar-restaurant that captivates its diners with the best burgers.', 1134202562, 3, 'The burgers are good, even the vegetarian one. The place is nice, located inside an old house, but the downside is the poor lighting. However, the highlight is the outdoor seating area, which is very well organized.', 'https://www.cronista.com/files/image/490/490714/637d19a93c3b4_700_454!.jpg?s=b1bdc4ca9974973305a192f8d567bb49&d=1669142956', 1426, 'https://arredondo.negocio.site/', 'Virrey Arredondo 2562, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Fat Broder', 'One of the most highly regarded burger joints in the city. The common denominator of our cuisine is respect for the product and its seasonality.', 1148325249, 4, 'Delicious! Excellent service, homemade sauces, and drinks! The burgers are delicious, and the fries are nice and crispy.', 'https://expressarte.com.ar/wp-content/uploads/fat-broder.jpg', 1419, 'https://www.fatbroder.com/', 'Charcas 3787, CABA ' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Burger Joint', 'The first gourmet burger joint in Argentina. Ranked 19th on The 50 Best Burgers In The World.', 1159315097, 5, 'The food is FANTASTIC and the quality of the ingredients should not be overlooked. Perfectly created burgers, perfectly serviced.', 'https://aguiarbuenosaires.com/wp-content/uploads/2016/01/Palermo_burguer_Joint2.jpg', 1414, 'https://www.instagram.com/burgerjointpalermo/?hl=en', 'Jorge Luis Borges 1766, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Italpast | Bistro Sur', 'Bistró Sur —one of the most spectacular gastronomic settings in the country— welcomes a new pop-up experience by Chef Pedro Picciau with Signature dishes and traditional flavors of Italian-Sardinian haute cuisine.', 1140109207, 5, 'Spectacular restaurant. A luxurious place: excellent food and outstanding service.', 'https://www.clarin.com/img/2022/11/18/CJyVe06Kd_720x0__1.jpg', 1419, 'https://www.faena.com/buenos-aires/dining/bistro-sur', 'Juana Manso 1450, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('D Oro Italian Bar', 'Fresh products, quality, and meticulous attention, preserving the essence throughout its history and achieving the true taste of Italian cuisine.', 1150514059, 4, 'Excellent ambiance, top-notch service, and very delicious food.', 'https://lh3.googleusercontent.com/p/AF1QipM_w31N3_npoV1QLaCWaBtXrMslDe0bF6y1ZCX8=s680-w680-h510', 1426, 'https://doroitalianbar.com/', 'Peru 159, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Il Gran Caruso', 'For over 37 years, Il Gran Caruso has maintained its position among the most dynamic Italian culinary experiences in Buenos Aires.', 47776633, 5, 'Best Italian meal ever outside Italy. Excellent food, excellent service, in a nice decor.', 'https://lh3.googleusercontent.com/p/AF1QipNa5-fNNxyQx0NEGXNwA6hylE6gIKWR7mnpyfyV=s680-w680-h510', 1414, 'http://www.grancaruso.com.ar/', 'El Salvador 5805, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('La Parolaccia', 'We are not a pasta restaurant... we are the pasta.', 48121053, 5, 'Fabulous meal. Reasonably prices, pleasant atmosphere. Great service. Excellent wines. Highly recommended.', 'https://scontent.faep11-2.fna.fbcdn.net/v/t31.18172-8/19243133_1693562824006292_807049453897215139_o.jpg?stp=cp0_dst-jpg_e15_p480x480_q65&_nc_cat=104&ccb=1-7&_nc_sid=dd7718&_nc_ohc=uZUYbZ9zOhwAX-FiwF-&_nc_ht=scontent.faep11-2.fna&oh=00_AfB3PzhRRdAgA3LVoV7fWU_3tqrZaSEznX6ldemnQLfqgQ&oe=65203677', 1419, 'https://www.laparolaccia.com/', 'Riobamba 1046, CABA'  );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Pasta', 'A high-quality pasta factory and restaurant where traditional Italian pasta styles blend with ideas and creations by Mauro Lacagnina.', 1155942641, 5, 'Delicious fresh pastas with a wide variety of sauces, the highlight of the evening was the tiramisu, we will be back!', 'https://lh3.googleusercontent.com/p/AF1QipPDepQ2UNR9mVK2yUVmD1Y1PHGDz9Yl-VAwJ14n=s680-w680-h510', 1426, 'https://lapasta.ar/', 'Salguero 2069, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Taquería Díaz', 'Authentic Mexican cuisine, its irresistible micheladas are offered and an atmosphere is comfortable.', 1157696559, 4, 'We will be back, the excellent margaritas, the abundant, fresh and very tasty food.', 'https://recetasveganas.net/wp-content/uploads/2020/07/recetas-tacos-sin-carne-vegetariano-alubias-aguacate-tomate-olivas2.jpg', 1414, 'https://www.instagram.com/taqueriadiaz/?hl=es-la', 'Av. Monroe 3915, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('María Barrera', 'History and flavor are combined, and it is condensed into an experience of several times in which Mexican regionalism is tested twice a week behind closed doors. Every Thursday and Saturday is a different experience, both in the dishes and in the context that accompanies it.', 1122812962, 5, 'I have already gone many times and I will return as many cycles as I can.', 'https://media-cdn.tripadvisor.com/media/photo-s/29/07/91/59/historicas-a-pasos-donde.jpg', 1426, 'https://www.instagram.com/mariabarrerasosa/?igshid=YmMyMTA2M2Y%3D', 'Av. Cabildo 101, CABA'  );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('La Fabrica del Taco', 'From the deepest roots of Mexican culture comes an authentic meal for your taste buds. Made by Mexicans for the whole world.', 1176198603, 5, 'The food is very delicious, good prices, great service, and a nice atmosphere.', 'https://recetinas.com/wp-content/uploads/2022/06/tacos-mexicanos.jpg.webp', 1419, 'http://lafabricadeltaco.com/#home', 'Mercedes 3942, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES (' Che Taco', 'Traditional Mexican cuisine made and served by Mexicans.', 1137906835, 4, 'Very delicious food, generous portions, excellent service, and affordable prices.', 'https://img.chilango.com/2017/09/chetito.jpg', 1414, 'https://www.instagram.com/chetaco/', 'Balcarce 873, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Taco N Todo', 'Whether you are looking for a quick lunch or a relaxed dinner, this Mexican cuisine restaurant offers an experience where the authenticity of flavors and Mexican hospitality come together to transport you directly to this country full of tradition and taste.', 1149025773, 4, 'The guacamole sauce is always exquisite, but the portions are somewhat small.', 'https://10619-2.s.cdn12.com/rests/original/410_444694928.jpg', 1419, 'https://www.instagram.com/tacontodocaballito/', 'Av. Juan Bautista Alberdi 698, CABA'  );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Fukuro Noodle Bar', 'In this establishment, you can discover authentic Japanese and Taiwanese cuisines. Eating their flavorful pork ramen, perfectly crafted bao dumplings, and surprising laing is a unique experience here.', 1131994095,	4, 'I ve been several times already, and the spicy ramen is one of the best I ve tried in Buenos Aires. Highly recommended.', 'https://picaar.com/wp-content/uploads/2019/05/fukuro-noodle-bar.jpg', 1426, 'https://www.instagram.com/fukuronoodlebar/?hl=es', 'Costa Rica 5514, CABA' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Cantina Sunae', 'A unique restaurant featuring Filipino, Asian, Thai, and Vietnamese cuisine in the best area of Buenos Aires.', 1147768122, 5, 'Everything we ate was excellent, the service was fantastic, the place is beautifully decorated. It is a pleasure to go for dinner to places like this.', 'https://www.asiancantina.com/wp-content/uploads/2019/10/home_1.jpg', 1414, 'https://www.asiancantina.com/', 'Humboldt 1626, CABA.' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('San Telmo Shokudo', 'Restaurant specializing in traditional Japanese sushi.', 1143619227, 4, 'Excellent ambiance and service, very good portions and quality, prices in line with the service, recommended for a couple is outing' , 'https://media-cdn.tripadvisor.com/media/photo-s/0d/ce/73/9c/ta-img-20161205-133706.jpg', 1419, 'https://www.facebook.com/santelmoshokudo/', 'Defensa 910, CABA.' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Nanten sushi', 'Tea house, sushi, and traditional Japanese cuisine.', 1148273072, 5, 'You can tell the food is fresh, made-to-order, and of good quality.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQs_KK80PcYALfBVDS2EZXCGjm4KGxjkP4P2Q9-lTa3gm2oV5P-eShBBipRA_2PtRPtaho&usqp=CAU', 1426, 'https://www.instagram.com/nantensushi/?igshid=ZDc4ODBmNjlmNQ%3D%3D', 'Pedro Morán 3243, CABA.' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('KOI Dumplings', 'Its a street food experience that brings together Asian dishes with Argentine flavors, blending both cuisines and international techniques to offer a unique identity.', 1168538908, 4, 'The gyoza is very delicious and diverse, just like the ramen.', 'https://siegerguide.com/wp-content/uploads/2020/03/Koi-Beer-Dumplings-2.jpg', 1414, 'https://koidumplings.com/', ' Donado 2007, CABA.' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Casa SaltShaker', 'We offer a unique social and dining experience, sharing a table with other guests in our home.', 1100000000, 5, 'A unique place with a great selection of wines and good food, where you can enjoy and have conversations.', 'https://www.casasaltshaker.com/wp-content/uploads/2021/10/210916-roasted-abadejo-textures-of-carrot.jpg', 1419, '	https://www.casasaltshaker.com/', 'Pres. J.E. Uriburu 1500, CABA.' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Tanta', 'We celebrate as a family the cuisine and its diversity, especially the homemade Peruvian food, the kind of food our mothers and grandmothers have prepared for us all our lives.', 1127686063, 5, 'Very nice place, exquisite dishes, excellent service from reception to waitstaff, very good price-quality ratio.', 'https://media-cdn.tripadvisor.com/media/photo-s/17/4d/0e/5f/salon-con-jardin-interior.jpg', 1426, 'https://www.tanta.com.ar/', 'Esmeralda 938, CABA.' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Che Peru', 'It is a culinary round trip between Argentina and Peru, with no starting point or destination port.', 1153896162, 4, 'Peruvian food, very delicious, plentiful, and excellent value for money.', 'https://cheperu.com.ar/img/gente.JPG', 1414, 'https://cheperu.com.ar/?gclid=Cj0KCQjwi7GnBhDXARIsAFLvH4mJhr4Bbe5YbTPuckfg9PyjmEIdMCIpiqCagugMdWXoGg4WQ3ubR1EaAv5XEALw_wcB', 'Guido 1962, CABA.' );
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Imperio Del Sol', 'If you are in the mood for spicy and fiery South American cuisine, you have come to the right place.', 1147813394, 4, 'Good Peruvian food, bought for takeout, and the portions were generous.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSZ-OzCqEK392ZY9m44TczUD2RSalv4g890Qm6fxJpjJMkW-Vvz97GpUMSqbVe6AS2sug&usqp=CAU', 1419, 'https://carta.menu/restaurants/ciudad-autonoma-de-buenos-aires/el-imperio-del-sol', 'Amenábar 2415, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Kamay Lounge', 'Authentic Peruvian Creole and Nikkei cuisine with an excellent quality-price ratio.',  1168059039, 4, 'The food was excellent. Everything was delicious, and the drinks were also very tasty and unique. A very good quality-price ratio.', 'https://media-cdn.tripadvisor.com/media/photo-s/28/27/5d/47/de-lejos-como-peruana.jpg', 1426, 'https://www.instagram.com/kamaylounge/?hl=es', 'Marcelo Torcuato de Alvear 975, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('El pobre Luis', 'Down-to-earth, vibrant restaurant & sports bar specializing in hearty grills & BBQ.', 1147805847, 4, 'Not a very known restaurant but surely a must visit one! The prices are very cheap compared to other restaurants in Buenos Aires and the meat is better than most of them!', 'https://10619-2.s.cdn12.com/rests/original/304_514128193.jpg', 1414, 'https://www.facebook.com/elpobreluisparrilla/', 'Arribeños 2393, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Los Chanchitos', 'Bodegon-style grill restaurant, grilled meats, milanese, homemade pasta.', 1148544030, 4, 'Just too good, great value for money, high quality ingredients and the best service. This place is a locals go to place, that is for sure.', 'https://www.rutacoop.com.ar/media/cooperativas/14.2.jpg', 1419, 'https://www.facebook.com/LosChanchitosCooperativaLimitada/', 'Av. Angel Gallardo 601, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Don Zoilo', 'Traditional Buenos Aires still life founded in 1989.', 1145881194, 4, 'Wonderful place. Service can be slow, but the food is worth the wait. Excellent prices also. Probably the only higher-end parilla place we plan to go to in Buenos Aires from now on.', 'https://turismo.buenosaires.gob.ar/sites/turismo/files/parrilla_don_zoilo_980_salon.jpg', 1426, 'https://www.instagram.com/donzoilo.ok', 'Av. Dr. Honorio Pueyrredón 1406, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('El ferroviario', 'Down-to-earth, railroad-themed eatery with a varied menu featuring grilled meats & pasta.', 1130597666, 4, 'Very authentic Parilla with an excellent reputation. The place offers a very local expiration away from tourist traps.  The service was quick and nice.', 'https://www.altagracianoticias.com/wp-content/uploads/2019/02/WhatsApp-Image-2019-02-23-at-13.22.34-1.jpeg', 1419, 'https://elferroviarioparrilla.com/', 'Av. Reservistas Argentinos 219, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('La Cabrera', 'Easygoing Argentinian restaurant specializing in grilled meats, with wood-lined decor & a terrace.', 1148310325, 4, 'The place is excellent, lots of meats and lots of wines. The meat was wonderful and the service provided by Miguel was incredible too. The structure and decoration are also beautiful, very clean.', 'https://turismo.buenosaires.gob.ar/sites/turismo/files/lacabrera980.jpg', 1414, 'https://www.lacabrera.com.ar', 'José A. Cabrera 5127, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('El Burladero', 'Cozy restaurant featuring traditional Spanish cuisine amid dark wood furnishings.', 1136912717, 4, 'Delicious food with abundant portions. Prices are fair given the quality of food and service. The staff is very attentive and helpful when ordering off the menu. Would recommend if you are looking for Spanish food such as paella and tapas.', 'https://fotos.perfil.com/2012/09/01/trim/1280/720/resto-el-burladero.jpg', 1426, 'https://www.elburladero.com.ar', 'Pres. José Evaristo Uriburu 1488, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('La Mar', 'Refined option focusing on seasonal seafood, ceviche & small plates in a stylish space with a patio.', 1147765543, 4, 'I m not sure words will do justice for the experience I had. From the moment I stepped in the door, the atmosphere was inviting and I felt instantly welcomed. The staff were friendly, knowledgeable and eager to assist with any questions I had.', 'https://s3.amazonaws.com/fathom_media/photos/buenos-aires-la_mar-lead.jpg.1200x800_q85_crop.jpg', 1414, 'https://www.lamarcebicheria.com.ar', 'Arévalo 2024, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Puerto Cristal', 'Classic riverside eatery offering a robust wine list & international fare, plus a terrace.', 1143313669, 4, 'Wow what a great place.   Some other features I admired were the English menu, the harbor view, and the great service. It is worth dining here.', 'https://i.pinimg.com/originals/50/ae/0c/50ae0ca1fd08552accc98bad88b5fc92.jpg', 1419, 'https://www.puerto-cristal.com.ar', 'Av. Alicia Moreau de Justo 1082, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Chipper', 'Relaxed Caribbean restaurant serving creative meat dishes, seafood & desserts, plus cocktails.', 1126998173, 4, 'This was one of the best meals I had while on vacation in BA. I had the grilled fish of the day and it was wonderful.  The atmosphere was lovely. I will certainly go back when I am in the area.', 'https://media-cdn.tripadvisor.com/media/photo-s/1a/db/ae/97/terraza.jpg', 1426, 'https://www.instagram.com/chipperseafood/?hl=es-la', 'Humboldt 1895,  CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Fishers', 'Fish & chips restaurant', 1165443729, 4, 'The food is very tasty and the guy who serves is very friendly, I highly recommend it!!', 'https://lh3.googleusercontent.com/p/AF1QipM1p0t7OYMa97Ph1zmQH9U_VLDdnjxndan_3x5W=s680-w680-h510', 1414, 'https://www.instagram.com/fishers.arg/', 'Migueletes 796,  CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Tandoor', 'Indian specialties, desserts & wine are offered at this warm, white-tablecloth restaurant.', 1148213689, 4, 'Been getting delivery from this place since ages. This is my first time going here in person. The service was amazing. I recommend the chicken tikka masala. Atmosphere is relaxed and cozy, perfect for couples.', 'https://media-cdn.tripadvisor.com/media/photo-s/09/5e/e5/44/tandoor.jpg', 1419, 'http://www.tandoor.com.ar', 'Laprida 1293, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Delhi Mahal', 'Authentic Indian food.', 1148136548, 4, 'This was my go to place while my time in Buenos Aires. It serves the best Indian food in BA. The staff is very friendly Sameer and Asif gave suggestions to try different dishes that were delicious.', 'https://media-cdn.tripadvisor.com/media/photo-s/13/d3/01/93/20180723-200825-largejpg.jpg', 	1426, 'https://www.facebook.com/pages/delhi-mahal/202198679931369', 'Av. Córdoba 1147, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Gran Dabbang', 'Really unique, fantastic Indian fusion.', 1135010481, 4, 'A must try place!! Incredible flavours with creative blends of Indian and South American elements.', 'https://lh3.googleusercontent.com/p/AF1QipMsOiGMdSt-pB17sdh94VXitvgCLS3nkYKIz1Xf=s680-w680-h510', 1414, 'https://www.instagram.com/DABBANG_/', 'Av. Raúl Scalabrini Ortiz 1543,CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Mumbai Indian Food', 'Experience the beauty of Indian art forms though music and dance.', 1147759791, 4, 'The best Indian restaurant in BA so far, very happy with the garlic naan and lamb curry, will come here to eat again for sure.', 'https://lh3.googleusercontent.com/p/AF1QipPxMpoOx7su-WA_IxeNcsjFV6rDU0cmKro266vq=s680-w680-h510', 1414, 'https://www.facebook.com/mumbai.baires/?locale=es_LA', 'Honduras 5684, CABA.');
INSERT INTO restaurant (restaurant_name, description, phone_number, rating, review, photo_path, zip_code, home_page, address) VALUES ('Delhi Masala', 'Traditional indian restaurant.', 1143003790, 4, 'Absolutely delicious food, full of flavours and spices.', 'https://lh3.googleusercontent.com/p/AF1QipMRBWeSZ03CuyBXQT-_imsstoNzm7rMKHzkPmXp=s680-w680-h510', 1414, 'https://www.instagram.com/delhi.masala/', 'Defensa 714,  CABA.');

INSERT INTO user_type_of_food(user_id,type_id) VALUES (1,1);
INSERT INTO user_type_of_food(user_id,type_id) VALUES (1,2);
INSERT INTO user_type_of_food(user_id,type_id) VALUES (1,5);
INSERT INTO user_type_of_food(user_id,type_id) VALUES (1,8);

INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (1,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (1,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (1,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (2,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (2,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (2,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (2,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (3,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (3,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (3,5);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (3,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (4,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (4,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (4,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (5,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (5,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (5,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (6,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (6,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (6,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (7,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (7,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (7,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (8,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (8,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (8,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (8,8);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (8,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (9,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (9,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (9,5);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (10,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (10,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (10,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (10,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (11,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (11,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (11,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (11,4);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (11,5);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (11,6);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (11,10);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (11,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (12,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (12,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (12,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (12,4);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (12,5);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (12,6);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (12,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (13,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (13,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (13,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (13,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (14,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (14,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (14,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (14,6);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (14,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (15,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (15,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (15,7);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (15,9);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (15,10);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (16,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (16,4);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (17,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (17,4);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (18,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (18,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (18,4);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (19,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (19,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (19,4);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (20,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (20,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (20,4);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (21,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (21,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (21,5);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (22,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (22,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (22,5);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (23,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (23,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (23,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (23,5);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (24,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (24,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (24,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (24,5);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (25,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (25,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (25,5);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (26,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (26,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (26,6);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (26,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (27,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (27,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (27,6);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (27,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (28,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (28,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (28,6);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (28,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (29,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (29,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (29,6);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (30,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (30,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (30,6);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (31,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (31,7);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (31,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (32,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (32,7);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (33,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (33,7);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (33,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (34,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (34,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (34,7);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (35,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (35,7);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (36,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (36,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (36,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (36,8);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (37,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (37,8);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (38,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (38,8);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (38,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (39,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (39,8);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (39,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (40,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (40,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (40,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (40,8);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (40,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (41,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (41,9);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (42,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (42,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (42,9);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (43,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (43,9);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (43,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (44,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (44,9);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (45,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (45,9);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (45,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (46,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (46,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (46,10);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (47,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (47,10);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (48,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (48,10);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (49,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (49,10);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (50,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (50,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (50,10);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (51,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (51,11);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (52,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (52,11);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (52,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (53,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (53,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (53,11);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (53,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (54,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (54,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (54,11);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (54,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (55,11);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (55,13);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (56,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (56,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (56,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (56,12);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (57,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (57,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (57,12);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (58,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (58,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (58,12);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (59,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (59,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (59,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (59,12);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (60,1);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (60,2);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (60,3);
INSERT INTO restaurant_type_of_food (restaurant_id, type_id) VALUES (60,12);




--ROLLBACK;
COMMIT TRANSACTION;
